[package]
name = "aasvg"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["chillcicada"]
license = "MIT"
description = "Convert ASCII art diagrams into SVG by aasvg-rs"

homepage = "https://github.com/chillcicada/typst-aasvg"
repository = "https://github.com/chillcicada/typst-aasvg"
keywords = ["wasm", "aasvg"]
